import { BIBLE_CANON } from "@/lib/bible/canon";

/** Identifiants OSIS (concordance.bible / Crosswire) → code livre AGAPE. */
const OSIS_TO_CODE: Record<string, string> = {
  Gen: "gen",
  Exod: "exo",
  Lev: "lev",
  Num: "num",
  Deut: "deu",
  Josh: "jos",
  Judg: "jdg",
  Ruth: "rut",
  "1Sam": "1sa",
  "2Sam": "2sa",
  "1Kgs": "1ki",
  "2Kgs": "2ki",
  "1Chr": "1ch",
  "2Chr": "2ch",
  Ezra: "ezr",
  Neh: "neh",
  Esth: "est",
  Job: "job",
  Ps: "psa",
  Prov: "pro",
  Eccl: "ecc",
  Song: "sng",
  Isa: "isa",
  Jer: "jer",
  Lam: "lam",
  Ezek: "ezk",
  Dan: "dan",
  Hos: "hos",
  Joel: "jol",
  Amos: "amo",
  Obad: "oba",
  Jonah: "jon",
  Mic: "mic",
  Nah: "nah",
  Hab: "hab",
  Zeph: "zep",
  Hag: "hag",
  Zech: "zec",
  Mal: "mal",
  Matt: "mat",
  Mark: "mrk",
  Luke: "luk",
  John: "jhn",
  Acts: "act",
  Rom: "rom",
  "1Cor": "1co",
  "2Cor": "2co",
  Gal: "gal",
  Eph: "eph",
  Phil: "php",
  Col: "col",
  "1Thess": "1th",
  "2Thess": "2th",
  "1Tim": "1ti",
  "2Tim": "2ti",
  Titus: "tit",
  Phlm: "phm",
  Heb: "heb",
  Jas: "jas",
  "1Pet": "1pe",
  "2Pet": "2pe",
  "1John": "1jn",
  "2John": "2jn",
  "3John": "3jn",
  Jude: "jud",
  Rev: "rev",
};

export function resolveOsisBook(osisId: string) {
  const code = OSIS_TO_CODE[osisId];
  if (!code) return null;
  return BIBLE_CANON.find((b) => b.code === code) ?? null;
}
